### ISSUE TITLE
Unable to run Example project

### ISSUE THREAD

**Issue by Natelegreat1** [Mastercard/oauth1-signer-swift#5]
### Setup
Xcode 12.2 (12B45b)

### Issue
Hello.
I am trying to run the sample (Example) project.
I have added my consumerKey, private key certificate & key password.
I have tried several services for `urlString`:
- https://api.mastercard.com/openbanking/sandbox/connect/api/
- https://sandbox.api.mastercard.com/accounts/consents
- https://sandbox.api.mastercard.com/notifications

No matter what I try, I get the following error:
```Alamofire.AFError.responseSerializationFailed(reason: Alamofire.AFError.ResponseSerializationFailureReason.jsonSerializationFailed(error: Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 0." UserInfo={NSDebugDescription=Invalid value around character 0.}))```

Any ideas?

**Comment by piyuhirpara** [comment]
@Natelegreat1 Which Mastercard API you are trying to connect? From the response it looks like you are getting error response which isn't in JSON format.

**Comment by Natelegreat1** [comment]
@piyuhirpara I was trying:
- [Open Banking Connect Payment Initiation Service](https://developer.mastercard.com/open-banking-connect/documentation/aisfeatures/overview/)
- [Transaction Notifications](https://developer.mastercard.com/transaction-notifications/documentation/)

**Comment by piyuhirpara** [comment]
@Natelegreat1 

Could you please paste request response logs from the sample app for Open Banking service call.

For Transaction Notifications, correct end point is : https://sandbox.api.mastercard.com/cardbasedconsent/
For more details please refer documentation available [here](https://developer.mastercard.com/transaction-notifications/documentation/).

**Comment by Natelegreat1** [comment]
@piyuhirpara 
I am using https://api.mastercard.com/openbanking/sandbox/connect/api/
for *Open Banking service call* - same AFError.
Using https://sandbox.api.mastercard.com/cardbasedconsent/ for Transaction Notifications and also getting the same error.

Maybe you can spot something that I changed by mistake?
<img width="1792" alt="Screen Shot 2020-11-19 at 12 42 14 PM" src="https://user-images.githubusercontent.com/2666640/99703319-f88cb800-2a64-11eb-984b-dcb41d72e793.png">

**Comment by TutteRamson** [comment]
[Transaction Notification APIs](https://developer.mastercard.com/transaction-notifications/documentation/api-reference/endpoints/) support two calls.
```
GET https://sandbox.api.mastercard.com/cardbasedconsent/consents/{card_reference}
POST https://sandbox.api.mastercard.com/cardbasedconsent/transactions
```

The screenshot suggests that you are doing a **POST** on `https://sandbox.api.mastercard.com/cardbasedconsent` without the `transactions`, unless I miss seeing it the right way.

Could you please make the call using the [insomnia plugin](https://github.com/Mastercard/insomnia-plugin-mastercard-auth) first to make sure your keys work with the endpoint correctly before trying out the Swift library?

**Comment by piyuhirpara** [comment]
@Natelegreat1,

In Addition to above answer from Ramson,

You also need to change "payload" according to API endpoint requirement.
